### ISSUE TITLE
ValueError: No pixel size found!

### ISSUE THREAD

**Issue by YunanYe** [Oftatkofta/cellocity#22]
Hi, I'm trying to analyze cytoplasmic flow in my mouse oocyte images (timelapse) following the tutorial. 
However, when I import multipage TIFF or ome.tif files containing multiple frames, I get ValueError: No pixel size found! 
I don't know why this is happening. The files are either exported through Leica's Las X software as multi-page tiff, or bio-format imported into FIJI, then exported as ome.tif. But they both throw the same error code...
See attached for image properties. 

I'm using Spyder in Anaconda.

Help is much appreciated!
![OME properties](https://user-images.githubusercontent.com/84897639/119780684-78f90d80-bf0d-11eb-9c8b-4038473780af.png)

![tiff properties](https://user-images.githubusercontent.com/84897639/119780682-78607700-bf0d-11eb-87d4-9604d383ce77.png)

**Comment by Oftatkofta** [comment]
Hi, I have not tested importing from LAS X, however FIJI should work. If you open the file in FIJI using Bioformats importer does it have correct scaling if you hit shift+P?
![image](https://user-images.githubusercontent.com/6969742/119782823-e89ad880-becc-11eb-8394-5c3e6cf6e534.png)


Check the scaling and save as a normal .tif

**Comment by YunanYe** [comment]
Thanks! I can get past that part now by exporting as a normal .tif from FIJI
At the median filtering step, i get this: ValueError: seek of closed file
Any idea how I should fix this? Thanks again!

**Comment by YunanYe** [comment]
So if I skip the median filtering for now and run through the whole tutorial. I can get the .csv and .tif outputs. But how do I actually turn that into the vector visualization? Sorry I'm very noob to coding. 
![image](https://user-images.githubusercontent.com/84897639/119914156-f458ce80-bfa2-11eb-8c19-4ac0ca7c09f2.png)

I tried speed_analysis_ch0.draw_all_flow_frames_superimposed() and got an array output?

Many thanks!

**Comment by Oftatkofta** [comment]
> 
> 
> Thanks! I can get past that part now by exporting as a normal .tif from FIJI
> At the median filtering step, i get this: ValueError: seek of closed file
> Any idea how I should fix this? Thanks again!

Are you opening the TIF-file in a [with-statement](https://www.geeksforgeeks.org/with-statement-in-python/)? as in the tutorial?

> 
> I tried speed_analysis_ch0.draw_all_flow_frames_superimposed() and got an array output?
> 
That's good, you just need to display the array, or save it as a tif.

``` python
outarray=speed_analysis_ch0.draw_all_flow_frames_superimposed()
speed_analysis_ch0.saveFlowAsTif(outpath)
```

Or you can try to follow and adapt the code I made for [animating the Cellociy logo](https://github.com/Oftatkofta/cellocity/blob/master/tests/logo_maker.py).

> Sorry I'm very noob to coding.

...as was I until I had a similar problem that I had to solve for my thesis work, good luck!

**Comment by YunanYe** [comment]
Thank you very much!

I can save the array as a tif now, but it seems my sample might be too small (105x105 pixel)? Or is it possible to reduce the size of vectors so we can see where they are point to?

![image](https://user-images.githubusercontent.com/84897639/120058510-a7522680-c08e-11eb-85e7-1389137c5ad0.png)
![image](https://user-images.githubusercontent.com/84897639/120058617-850cd880-c08f-11eb-91eb-b5b0ea4ff8e3.png)

Btw, above is still obtained with skipping the median filter step. I'm using with statement just like the tutorial, but still says closed file :(
![image](https://user-images.githubusercontent.com/84897639/120058665-f3519b00-c08f-11eb-958d-15e9716b877e.png)

**Comment by Oftatkofta** [comment]
Strange, I will have to look in to it.

Vector representation sizes are change by draw_all_flow_frames_superimposed(scalebarFlag=False, scalebarLength=10, **kwargs)

the **kwargs (a dictionary) are passed on to an internal function and have the following defaults (which can be changed):

kwargs={step=15, scale=20, line_thicknes=2}

**Comment by YunanYe** [comment]
Thanks again Jens..Sorry it looks so close to working but somehow we are back with another problem. I didn't change anything but somehow I now keep getting an error from the first line. I tried with running in Spyder and Jupyter notebook online and am getting the same problem. Do you have a clue why this is the case? 

![image](https://user-images.githubusercontent.com/84897639/120406003-3d3ac980-c38d-11eb-8871-f3b3fb650928.png)

**Comment by Oftatkofta** [comment]
You need to do a pip install cellocity first in your environment.

**Comment by YunanYe** [comment]
Thanks, working now. Just wondering, is it possible to add arrows to the vectors to get direction info? Like this
![image](https://user-images.githubusercontent.com/84897639/120565964-89e7d880-c451-11eb-92e4-f11a7efb6e52.png)

**Comment by Oftatkofta** [comment]
Yes it is, the vectors are drawn with cv.polylines() from openCV. You need to copy or modify the code for the  ._draw_flow_frame() method of the FlowAnalysis class.

https://github.com/Oftatkofta/cellocity/blob/a743dadcf439f1439dab1dd2e868939f527b8907/cellocity/analysis.py
